// data
var data = [
  //Letters
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/A.jpg",
    audio: "audios/alphabet/a.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/B.jpg",
    audio: "audios/alphabet/b.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/C.jpg",
    audio: "audios/alphabet/c.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/D.jpg",
    audio: "audios/alphabet/d.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/E.jpg",
    audio: "audios/alphabet/e.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/F.jpg",
    audio: "audios/alphabet/f.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/G.jpg",
    audio: "audios/alphabet/g.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/H.jpg",
    audio: "audios/alphabet/h.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/I.jpg",
    audio: "audios/alphabet/i.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/J.jpg",
    audio: "audios/alphabet/j.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/K.jpg",
    audio: "audios/alphabet/k.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/L.jpg",
    audio: "audios/alphabet/l.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/M.jpg",
    audio: "audios/alphabet/m.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/N.jpg",
    audio: "audios/alphabet/n.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/O.jpg",
    audio: "audios/alphabet/o.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/P.jpg",
    audio: "audios/alphabet/p.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/Q.jpg",
    audio: "audios/alphabet/q.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/R.jpg",
    audio: "audios/alphabet/r.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/S.jpg",
    audio: "audios/alphabet/s.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/T.jpg",
    audio: "audios/alphabet/t.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/U.jpg",
    audio: "audios/alphabet/u.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/V.jpg",
    audio: "audios/alphabet/v.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/W.jpg",
    audio: "audios/alphabet/w.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/X.jpg",
    audio: "audios/alphabet/x.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/Y.jpg",
    audio: "audios/alphabet/y.mp3",
  },
  {
    name:"",
    type: "letter",
    image: "photos/alphabet/Z.jpg",
    audio: "audios/alphabet/z.mp3",
  },
  
  //animals
  {
    name: "Cat",
    type: "animal",
    image: "photos/animals/cat.jpg",
    audio: "audios/animals/cat.mp3",
  },
  {
    name: "Rabbit",
    type: "animal",
    image: "photos/animals/rabbit.jpg",
    audio: "audios/animals/rabbit.mp3",
  },
  {
    name: "Dog",
    type: "animal",
    image: "photos/animals/dog.jpg",
    audio: "audios/animals/dog.mp3",
  },
  {
    name: "Chicken",
    type: "animal",
    image: "photos/animals/chicken.jpg",
    audio: "audios/animals/chicken.mp3",
  },
  {
    name: "Turkey",
    type: "animal",
    image: "photos/animals/turkey.png",
    audio: "audios/animals/turkey.mp3",
  },
  {
    name: "Goat",
    type: "animal",
    image: "photos/animals/goat.jpg",
    audio: "audios/animals/goat.mp3",
  },
  {
    name: "Sheep",
    type: "animal",
    image: "photos/animals/sheep.jpg",
    audio: "audios/animals/sheep.mp3",
  },
  {
    name: "Cow",
    type: "animal",
    image: "photos/animals/cow.jpg",
    audio: "audios/animals/cow.mp3",
  },
  {
    name: "Donckey",
    type: "animal",
    image: "photos/animals/donckey.jpg",
    audio: "audios/animals/donckey.mp3",
  },
  {
    name: "Horse",
    type: "animal",
    image: "photos/animals/horse.jpg",
    audio: "audios/animals/horse.mp3",
  },
  
  //Numbers
  {
    name:"",
    type: "number",
    image: "photos/numbers/0.jpg",
    audio: "audios/numbers/0.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/1.jpg",
    audio: "audios/numbers/1.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/2.jpg",
    audio: "audios/numbers/2.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/3.jpg",
    audio: "audios/numbers/3.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/4.jpg",
    audio: "audios/numbers/4.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/5.jpg",
    audio: "audios/numbers/5.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/6.jpg",
    audio: "audios/numbers/6.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/7.jpg",
    audio: "audios/numbers/7.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/8.jpg",
    audio: "audios/numbers/8.mp3",
  },
  {
    name:"",
    type: "number",
    image: "photos/numbers/9.jpg",
    audio: "audios/numbers/9.mp3",
  },
];
